name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - conda
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - fmt
  - icu
  - idna
  - krb5
  - libarchive
  - libcurl
  - libcxx
  - libedit
  - libev
  - libffi
  - libiconv
  - libmamba
  - libmambapy
  - libnghttp2
  - libsolv
  - libsqlite
  - libssh2
  - libxml2
  - libzlib
  - lz4-c
  - lzo
  - mamba
  - ncurses
  - openssl
  - pip
  - pluggy
  - pybind11-abi
  - pycosat
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - python_abi
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - ruamel_yaml
  - setuptools
  - tk
  - toolz
  - tqdm
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - yaml-cpp
  - zstandard
  - zstd
